# Generated by Django 2.1.7 on 2019-06-07 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_urldata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urldata',
            old_name='tag11',
            new_name='shopplace1',
        ),
        migrations.RenameField(
            model_name='urldata',
            old_name='tag12',
            new_name='shopplace2',
        ),
        migrations.RenameField(
            model_name='urldata',
            old_name='tag13',
            new_name='shopplace3',
        ),
        migrations.RenameField(
            model_name='urldata',
            old_name='tag14',
            new_name='shopplace4',
        ),
        migrations.RenameField(
            model_name='urldata',
            old_name='tag15',
            new_name='shopplace5',
        ),
        migrations.AlterField(
            model_name='urldata',
            name='tag1',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='urldata',
            name='tag10',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='urldata',
            name='tag2',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='urldata',
            name='tag3',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='urldata',
            name='tag4',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='urldata',
            name='tag5',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='urldata',
            name='tag6',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='urldata',
            name='tag7',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='urldata',
            name='tag8',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='urldata',
            name='tag9',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
