# Generated by Django 2.1.7 on 2019-06-07 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0005_auto_20190607_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='urldata',
            name='shopname',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
